/**
 * LocalizationManager.swift → ES module
 * Supports %@ / %d style format strings from the iOS app.
 */
import { Language } from '../src/Language.js';

const turkishStrings = {
  title: 'QuickMind',
  easy: 'Kolay',
  medium: 'Orta',
  hard: 'Zor',
  start: 'Başla',
  restart: 'Yeniden Başla',
  mainMenu: 'Ana Menüye Dön',
  scoreboard: 'Skor Tablosu',
  settings: 'Ayarlar',
  round: 'Tur',
  score: 'Puan',
  correct: 'Doğru! 🎉',
  points: 'puan',
  wrong: 'Yanlış! Oyun Bitti 😔',
  tapEmoji: "Lütfen '%@' tıklayın",
  memoryQuestion: '%d tur önce hangi cevabı vermiştin?',
  selectMin: 'En küçük sayıyı seçin',
  selectMax: 'En büyük sayıyı seçin',
  tapColor: "Lütfen '%@' rengine tıklayın",
  timeUp: 'Süre Doldu! ⏰',
  close: 'Kapat',
  privacyPolicy: 'Gizlilik Politikası',
  settingsTitle: 'Ayarlar',
  settingsDescription: 'Oyun modlarını seçerek hangi tür soruların çıkacağını belirleyebilirsiniz.',
  mathMode: 'Matematik',
  mathDescription: 'Toplama, çıkarma, çarpma ve bölme işlemleri içeren sorular',
  colorMode: 'Renk',
  colorDescription: 'Belirtilen rengi bulmanız istenir',
  emojiMode: 'Emoji',
  emojiDescription: 'Belirtilen emojiyi bulmanız istenir',
  minMaxMode: 'En Küçük/En Büyük',
  minMaxDescription: 'Verilen sayılar arasından en küçük veya en büyük sayıyı bulmanız istenir',
  memoryMode: 'Hafıza',
  memoryDescription: 'Önceki soruların cevaplarını hatırlamanız istenir',
  addition: 'Toplama',
  subtraction: 'Çıkarma',
  multiplication: 'Çarpma',
  division: 'Bölme',
  language: 'Dil',
  languageDescription: 'Uygulama dilini seçin',
  scoreboardTitle: 'Skor Tablosu',
  difficulty: 'Zorluk',
  date: 'Tarih',
  seconds: 'saniye',
  noGamesYet: 'Henüz oyun oynanmamış',
  emoji_smiling_face: 'Gülen Yüz',
  emoji_heart: 'Kalp',
  emoji_star: 'Yıldız',
  emoji_fire: 'Ateş',
  emoji_party: 'Parti',
  emoji_rocket: 'Roket',
  emoji_game: 'Oyun',
  emoji_apple: 'Elma',
  emoji_cat: 'Kedi',
  emoji_moon: 'Ay',
  emoji_dog: 'Köpek',
  emoji_sun: 'Güneş',
  emoji_music: 'Müzik',
  emoji_trophy: 'Kupa',
  emoji_balloon: 'Balon',
  emoji_pizza: 'Pizza',
  emoji_ball: 'Top',
  emoji_palette: 'Palet',
  emoji_phone: 'Telefon',
  emoji_dart: 'Dart',
  emoji_panda: 'Panda',
  emoji_lion: 'Aslan',
  emoji_frog: 'Kurbağa',
  emoji_penguin: 'Penguen',
  emoji_unicorn: 'Tekboynuz',
  emoji_bee: 'Arı',
  emoji_butterfly: 'Kelebek',
  emoji_flower: 'Çiçek',
  emoji_palm: 'Palmiye',
  emoji_wave: 'Dalga',
  emoji_snowman: 'Kardan Adam',
  emoji_circus: 'Sirk',
  emoji_theater: 'Tiyatro',
  emoji_guitar: 'Gitar',
  emoji_trumpet: 'Trompet',
  emoji_violin: 'Keman',
  emoji_basketball: 'Basketbol',
  emoji_tennis: 'Tenis',
  emoji_volleyball: 'Voleybol',
  emoji_dice: 'Zar',
  emoji_card: 'Oyun Kartı',
  emoji_joker: 'Joker',
  emoji_gift: 'Hediye',
  color_red: 'Kırmızı',
  color_blue: 'Mavi',
  color_green: 'Yeşil',
  color_yellow: 'Sarı',
  color_orange: 'Turuncu',
  color_purple: 'Mor',
  color_pink: 'Pembe',
  color_brown: 'Kahverengi',
  color_black: 'Siyah',
  color_white: 'Beyaz',
  color_gray: 'Gri',
  color_teal: 'Turkuaz',
  color_navy: 'Lacivert',
  color_light_green: 'Açık Yeşil',
  color_light_blue: 'Açık Mavi',
};

const englishStrings = {
  title: 'QuickMind',
  easy: 'Easy',
  medium: 'Medium',
  hard: 'Hard',
  start: 'Start',
  restart: 'Restart',
  mainMenu: 'Main Menu',
  scoreboard: 'Scoreboard',
  settings: 'Settings',
  round: 'Round',
  score: 'Score',
  correct: 'Correct! 🎉',
  points: 'points',
  wrong: 'Wrong! Game Over 😔',
  tapEmoji: "Please tap '%@'",
  memoryQuestion: 'What answer did you give %d rounds ago?',
  selectMin: 'Select the smallest number',
  selectMax: 'Select the largest number',
  tapColor: "Please tap the '%@' color",
  timeUp: "Time's Up! ⏰",
  close: 'Close',
  privacyPolicy: 'Privacy Policy',
  settingsTitle: 'Settings',
  settingsDescription: 'You can choose which types of questions will appear by selecting game modes.',
  mathMode: 'Math',
  mathDescription: 'Questions involving addition, subtraction, multiplication, and division',
  colorMode: 'Color',
  colorDescription: 'You are asked to find the specified color',
  emojiMode: 'Emoji',
  emojiDescription: 'You are asked to find the specified emoji',
  minMaxMode: 'Min/Max',
  minMaxDescription: 'You are asked to find the smallest or largest number from the given numbers',
  memoryMode: 'Memory',
  memoryDescription: 'You are asked to remember the answers to previous questions',
  addition: 'Addition',
  subtraction: 'Subtraction',
  multiplication: 'Multiplication',
  division: 'Division',
  language: 'Language',
  languageDescription: 'Select the application language',
  scoreboardTitle: 'Scoreboard',
  difficulty: 'Difficulty',
  date: 'Date',
  seconds: 'seconds',
  noGamesYet: 'No games played yet',
  emoji_smiling_face: 'Smiling Face',
  emoji_heart: 'Heart',
  emoji_star: 'Star',
  emoji_fire: 'Fire',
  emoji_party: 'Party',
  emoji_rocket: 'Rocket',
  emoji_game: 'Game',
  emoji_apple: 'Apple',
  emoji_cat: 'Cat',
  emoji_moon: 'Moon',
  emoji_dog: 'Dog',
  emoji_sun: 'Sun',
  emoji_music: 'Music',
  emoji_trophy: 'Trophy',
  emoji_balloon: 'Balloon',
  emoji_pizza: 'Pizza',
  emoji_ball: 'Ball',
  emoji_palette: 'Palette',
  emoji_phone: 'Phone',
  emoji_dart: 'Dart',
  emoji_panda: 'Panda',
  emoji_lion: 'Lion',
  emoji_frog: 'Frog',
  emoji_penguin: 'Penguin',
  emoji_unicorn: 'Unicorn',
  emoji_bee: 'Bee',
  emoji_butterfly: 'Butterfly',
  emoji_flower: 'Flower',
  emoji_palm: 'Palm',
  emoji_wave: 'Wave',
  emoji_snowman: 'Snowman',
  emoji_circus: 'Circus',
  emoji_theater: 'Theater',
  emoji_guitar: 'Guitar',
  emoji_trumpet: 'Trumpet',
  emoji_violin: 'Violin',
  emoji_basketball: 'Basketball',
  emoji_tennis: 'Tennis',
  emoji_volleyball: 'Volleyball',
  emoji_dice: 'Dice',
  emoji_card: 'Card',
  emoji_joker: 'Joker',
  emoji_gift: 'Gift',
  color_red: 'Red',
  color_blue: 'Blue',
  color_green: 'Green',
  color_yellow: 'Yellow',
  color_orange: 'Orange',
  color_purple: 'Purple',
  color_pink: 'Pink',
  color_brown: 'Brown',
  color_black: 'Black',
  color_white: 'White',
  color_gray: 'Gray',
  color_teal: 'Teal',
  color_navy: 'Navy',
  color_light_green: 'Light Green',
  color_light_blue: 'Light Blue',
};

export class LocalizationManager {
  constructor() {
    this.currentLanguage = Language.english;
  }

  localizedString(key) {
    const table = this.currentLanguage === Language.english ? englishStrings : turkishStrings;
    return table[key] ?? key;
  }

  /** Format iOS-style strings: %@ and %d placeholders in order */
  format(key, ...args) {
    let str = this.localizedString(key);
    for (const arg of args) {
      str = str.replace(/%[@d]/, String(arg));
    }
    return str;
  }
}
