/** Mirrors GameConstants.swift — emoji keys, color keys/hex, item count */

export const GameConstants = {
  numberOfItems: 15,

  emojis: [
    ['😀', 'emoji_smiling_face'],
    ['❤️', 'emoji_heart'],
    ['⭐', 'emoji_star'],
    ['🔥', 'emoji_fire'],
    ['🎉', 'emoji_party'],
    ['🚀', 'emoji_rocket'],
    ['🎮', 'emoji_game'],
    ['🍎', 'emoji_apple'],
    ['🐱', 'emoji_cat'],
    ['🌙', 'emoji_moon'],
    ['🐶', 'emoji_dog'],
    ['🌞', 'emoji_sun'],
    ['🎵', 'emoji_music'],
    ['🏆', 'emoji_trophy'],
    ['🎈', 'emoji_balloon'],
    ['🍕', 'emoji_pizza'],
    ['⚽', 'emoji_ball'],
    ['🎨', 'emoji_palette'],
    ['📱', 'emoji_phone'],
    ['🎯', 'emoji_dart'],
    ['🐼', 'emoji_panda'],
    ['🦁', 'emoji_lion'],
    ['🐸', 'emoji_frog'],
    ['🐧', 'emoji_penguin'],
    ['🦄', 'emoji_unicorn'],
    ['🐝', 'emoji_bee'],
    ['🦋', 'emoji_butterfly'],
    ['🌺', 'emoji_flower'],
    ['🌴', 'emoji_palm'],
    ['🌊', 'emoji_wave'],
    ['⛄', 'emoji_snowman'],
    ['🎪', 'emoji_circus'],
    ['🎭', 'emoji_theater'],
    ['🎸', 'emoji_guitar'],
    ['🎺', 'emoji_trumpet'],
    ['🎻', 'emoji_violin'],
    ['🏀', 'emoji_basketball'],
    ['🎾', 'emoji_tennis'],
    ['🏐', 'emoji_volleyball'],
    ['🎲', 'emoji_dice'],
    ['🎴', 'emoji_card'],
    ['🃏', 'emoji_joker'],
    ['🎁', 'emoji_gift'],
  ],

  /** UIColor → CSS hex approximations of iOS system colors */
  colors: [
    ['color_red', '#FF3B30'],
    ['color_blue', '#007AFF'],
    ['color_green', '#34C759'],
    ['color_yellow', '#FFCC00'],
    ['color_orange', '#FF9500'],
    ['color_purple', '#AF52DE'],
    ['color_pink', '#FF2D55'],
    ['color_brown', '#A2845E'],
    ['color_black', '#000000'],
    ['color_white', '#FFFFFF'],
    ['color_gray', '#8E8E93'],
    ['color_teal', '#5AC8FA'],
    ['color_navy', '#007AFFCC'],
    ['color_light_green', '#34C759B3'],
    ['color_light_blue', '#007AFF99'],
  ],
};
